version: '3'

services:
  mdchat_nginx:
    build: D:/Projects/mdchat-front/
    image: mdchat_http
    container_name: mdchat_nginx
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

  mysqldb:
    image: mysql:8
    container_name: mdchat_mysql
    volumes:
      - D:/VolMdChatMySQL:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - apinet
    environment:
      MYSQL_DATABASE: mdchat
      MYSQL_ROOT_PASSWORD: iA2YKJH;zED8n@e

  mdchat_api:
    image: mdchat_api
    ports:
      - 8080:8080
    networks:
      - apinet
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mdchat?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    depends_on:
      - mysqldb

networks:
  internalnet:
    driver: bridge
  apinet:
